name: Update Resources JSON

on:
  schedule:
    - cron: '0 6 * * 1' # Every Monday at 6am UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Debug env
        run: |
          echo "Checking for env overrides..."
          env | grep -i python || echo "No PYTHON-related env vars"


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
            
      - name: Debug Python Version
        run: python --version || echo "Python not installed yet"


      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Scraper
        run: python scripts/scrape_resources.py

      - name: Commit & Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add assets/data/resources.json
          git commit -m "Auto-update resources.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
