name: Update Resources JSON

on:
  schedule:
    - cron: '0 6 * * 1' # Every Monday at 6am UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Check for .python-version file
        run: |
          echo "Checking workspace for .python-version file..."
          find . -name ".python-version" || echo "No .python-version file found."
          cat .python-version || echo ".python-version does not exist or is empty."

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Scraper
        run: python scripts/scrape_resources.py

      - name: Commit & Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add assets/data/resources.json
          git commit -m "Auto-update resources.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
